# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Programming and Data Analytics for Scientists
tagline:          'A Jekyll theme'
description:      'Giving scientists the tools they need to use computers to do better science'
url:              http://ornl-training.github.io/
baseurl:          /training

author:
  name:           'Greg Watson'

github:
  repo:           https://github.com/ornl-training/ornl-training.github.io/tree/master

gems:
  - jekyll-redirect-from
